[versions]
springBootVersion = '3.5.7'
springBootDependencyManagementVersion = '1.1.7'
spotlessVersion = '8.1.0'

[libraries]
googleApiClient = { group = "com.google.api-client", name = "google-api-client", version = "2.8.1" }
googleOauthClientJetty = { group = "com.google.oauth-client", name = "google-oauth-client-jetty", version = "1.39.0" }
googleApiSheets = { group = "com.google.apis", name = "google-api-services-sheets", version = "v4-rev20251110-2.0.0" }
googleApiCalendar = { group = "com.google.apis", name = "google-api-services-calendar", version = "v3-rev20250404-2.0.0" }
googleApiDrive = { group = "com.google.apis", name = "google-api-services-drive", version = "v3-rev20251210-2.0.0" }
googleApiDocs = { group = "com.google.apis", name = "google-api-services-docs", version = "v1-rev20251110-2.0.0" }
googleMaps = { group = "com.google.maps", name = "google-maps-services", version = "2.2.0" }
fireBaseAdmin = { group = "com.google.firebase", name = "firebase-admin", version = "9.7.0" }
gcloudTestContainers = { group = "org.testcontainers", name = "gcloud", version = "1.21.3" }
instancio =  { group="org.instancio", name="instancio-junit", version="5.5.1"}
gcloudSecretManager = { group = "com.google.cloud", name = "spring-cloud-gcp-starter-secretmanager", version = "7.4.1" }
[bundles]

[plugins]
springBootPlugin =  { id = "org.springframework.boot", version.ref = "springBootVersion" }
springBootDependencyManagementPlugin =  { id = "io.spring.dependency-management", version.ref = "springBootDependencyManagementVersion" }
spotlessPlugin =  { id = "com.diffplug.spotless", version.ref = "spotlessVersion" }
